### ISSUE TITLE
Better implementation of `Ord` on natural numbers

### ISSUE THREAD

**Issue by jespercockx** [agda/agda2hs#107]
Currently, the `Ord` instance for natural numbers is defined through `ordFromLessThan`:

https://github.com/agda/agda2hs/blob/c23bc94c7113026c9428f4db4b044ca3d8c4d923/lib/Haskell/Prim/Ord.agda#L90-L91

This leads to less-than-optimal computational behaviour which complicates proofs, e.g. `max (suc x) (suc y)` is not definitionally equal to `suc (max x y)`. Since the `Nat` type is not present in Haskell and hence should purely be used for type-level expressions, it would make sense to replace the definition here with a hand-defined one.

**Comment by rashadg1030** [comment]
Hello, new to all this and thought I'd take on this issue since I want to learn more about Agda and use `agda2hs` for my own Haskell projects. I have a few questions:

- Shouldn't Agda's `Nat` type correspond to Haskell's `Natural` type from `GHC.Natural`? At least at the value-level.
- Also, shouldn't the equality be between `max (suc x) (suc y)` and `suc (max x y)`, not `suc (max x) (max y)`?
- Finally, by "hand-defined", I assume you mean defining the `Ord` record for `Nat` manually instead of using the `ordFromLessThan` function. Right? I just want to make sure I understand this correctly. I read in your blog post that Agda records correspond to Haskell typeclasses which I thought was cool.

Excuse me if these are not the best questions, I'm fairly new to Agda but I'd like to learn. Hopefully, I can work on this issue and learn more.

**Comment by jespercockx** [comment]
Thanks for your interest! To answer your questions:
- Making Agda's `Nat` correspond to Haskell's `Natural` is tricky because of how `Natural` is defined in Haskell:
  ```haskell
  -- Invariant: numbers <= WORD_MAXBOUND use the `NS` constructor
  data Natural
     = NS !Word#
     | NB !BigNat#
  ```
  This is quite far from how natural numbers are represented in Agda, so some things (in particular pattern matching on `zero`/`suc`) are difficult to translate. It might be better to define an alternative `Natural` type in Agda that is translated to `GHC.Natural` instead.
- Yes, that's correct, I'll fix it in the OP!
- Yes, that's correct.
