### ISSUE TITLE
Support pattern matching on `Natural`?

### ISSUE THREAD

**Issue by amesgen** [agda/agda2hs#117]
Suppose we have
```agda
fib : Nat → Nat
fib 0 = 0
fib 1 = 1
fib (suc (suc n)) = fib n + fib (suc n)
{-# COMPILE AGDA2HS fib #-}
```
Right now, this is translated to
```haskell
fib :: Natural -> Natural
fib zero = 0
fib (suc zero) = 1
fib (suc (suc n)) = fib n + fib (suc n)
```
which does not compile ofc. But this could be translated to very similar code which is actually compiling without warnings:
```haskell
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE ViewPatterns #-}

pattern Zero :: Natural
pattern Zero = 0

pattern Suc :: Natural -> Natural
pattern Suc n <- (minusOne -> Just n) where Suc n = n + 1

{-# COMPLETE Zero, Suc #-}

minusOne :: Natural -> Maybe Natural
minusOne n = if n >= 1 then Just (n - 1) else Nothing

fib :: Natural -> Natural
fib Zero = 0
fib (Suc Zero) = 1
fib (Suc (Suc n)) = fib n + fib (Suc n)
```

I think sth like this could be useful (e.g. inductively constructing trees of a certain height), but maybe it is too ad-hoc/magic?

**Comment by jespercockx** [comment]
This might be a nice idea, provided we also give Haskell implementations for the builtin functions on naturals in Agda (see https://github.com/agda/agda/blob/master/src/data/lib/prim/Agda/Builtin/Nat.agda)

**Comment by jespercockx** [comment]
The argument against this is that the goal of agda2hs is to write *Haskell* code in Agda syntax, while this is instead trying to encode an Agda feature into Haskell syntax. So in a sense this is the "wrong" thing to want, since the `Natural` type of Haskell is very rarely used compared to the `Nat` type in Agda.

**Comment by uncle-betty** [comment]
Maybe output the following Haskell code instead? Maybe that would look a little more idiomatic?

```
fib :: Natural -> Natural
fib 0 = 0
fib 1 = 1
fib n' | n' >= 2 = fib (n' - 2) + fib (1 + (n' - 2))
```
I.e.,

  * Matching with a constant natural number is preserved.
  * Matching with the i-th successor of a variable `n` results in a guard of `n' >= i`. And on the RHS, `n` would become `n' - i`.
  * `suc x` on the RHS becomes `1 + x`.

Of course then one could try to be even smarter and turn `(1 + (n' - 2))` into `(n' - 1)` or get rid of the `n' >= 2` guard as redundant in the case at hand.

I find naturals just very convenient to work with on the Agda side, when it comes to termination checking or induction proofs.

**Comment by uncle-betty** [comment]
Oh, boy... I took a look at the agda2hs code and it looks like implementing my proposal would litter all over the code.

* `compilePats` would have to record and return the guards.
* `compilePats` would also have to record and return how deeply each variable `x` is buried inside a pattern like `(suc (suc (... (suc x))))`, so that this depth can be subtracted from all occurrences of `x` on the RHS.
* `compileTerm` would have to know about the depth of each variable that occurs in a pattern, so that it can do the subtractions on the RHS.
* `compileTerm` would now also have to do de-Bruijn bookkeeping whenever it goes under a lambda.

That's a lot of extra stuff these functions would pass in and out. Stuff that would be irrelevant to any of the other use cases these functions cover. Maybe it's not worth the complication.

Which makes me curious about the workaround that you mentioned. But I seem to be missing something.

How would I use an erased Nat argument to help the termination checker? A typical use case would be: match an argument with `(suc n)` and then recurse with `n`, which is smaller than `(suc n)` and thus satisfies the termination checker. But I cannot pattern match with erased arguments, can I?

**Comment by jespercockx** [comment]
Perhaps we should first have a good story on how to handle guards in general (see https://github.com/agda/agda2hs/issues/77) and then revisit this issue.

Regarding the use of erased natural numbers: the trick is that the erased number should appear in the type of some other datatype that is *not* erased, so that in each clause there is only one of `zero`/`suc` possible based on the non-erased patterns. How to do it exactly is a bit fiddly though and depends on the function you want to write. A better way might be to use an erased accessibility predicate as it only has a single constructor so you can always match on it even when it's erased.

**Comment by uncle-betty** [comment]
Yes, agreed. It's probably best to figure out #77 first.

Thank you very much for your suggestions. I tried (and failed - see below), but ended up doing something simpler: use two versions of a function, one that matches with `suc`, one that doesn't, and trivially prove them equal. I can then prove things about the former, but export the latter to Haskell.

This completely solves the issue for my use cases. I'll look into automating some of this with reflection.

An example based on the factorial function:

```
module Test where

open import Haskell.Prelude
open import Haskell.Prim using (monusNat)

fac3 : Nat → Nat
fac3 0       = 1
fac3 (suc n) = suc n * fac3 n

{-# TERMINATING #-}
fac3' : Nat → Nat
fac3' 0 = 1
fac3' n = n * fac3' (monusNat n 1)

{-# COMPILE AGDA2HS fac3' #-}

fac3'≡fac3 : ∀ n → fac3' n ≡ fac3 n
fac3'≡fac3 zero = refl
fac3'≡fac3 (suc n) rewrite fac3'≡fac3 n = refl
```

My other two attempts were dead ends. I'm leaving them here, in case anybody is curious enough and feels inclined to take a look. Like I said, for me, the above works well.

This one looked really good at first, but Agda is smart enough to understand that `n` actually has to be `suc n'` in the second clause of `fac2'`, and thus pattern-matches with `suc n'` instead of just leaving the `n` there. And so, to my surprise, the Haskell code contained `suc n'`, not `n`.

```
data View : Nat → Set where
  vZero : View 0
  vSuc : (n : Nat) → View (suc n)

@0 view : (n : Nat) → View n
view zero    = vZero
view (suc n) = vSuc n

fac2' : (n : Nat) → (@0 v : View n) → Nat
fac2' 0 vZero     = 1
fac2' n (vSuc n') = n * fac2' n' (view n')

{-# COMPILE AGDA2HS fac2' #-}

fac2 : (n : Nat) → Nat
fac2 n = fac2' n (view n)

{-# COMPILE AGDA2HS fac2 #-}
```

I also tried accessibility. But then I realized that I would need `n - 1 < n` in the hole at the end of the second clause of `fac`. And that, in turn, would require knowing that `n` is actually `suc n`, i.e., it would require pattern matching with `suc n`.

```
LessThan : Nat → Nat → Set
LessThan x y = (x < y) ≡ True

data Acc (x : Nat) : Set where
  acc : (rs : (y : Nat) → LessThan y x → Acc y) → Acc x

fac : (n : Nat) → (@0 a : Acc n) → Nat
fac 0 (acc rs) = 1
fac n (acc rs) = n * fac (monusNat n 1) (rs (monusNat n 1) {!!})
```

Thanks again for your help! I appreciate it. It was really instructive to explore the latter two options.

**Comment by uncle-betty** [comment]
FWIW, this _almost_ works:

```
module Exp where

open import Agda.Builtin.Equality using (_≡_ ; refl)
open import Haskell.Prelude

data Zero? : Nat → Set where
  ≡0 : Zero? 0
  ≢0 : {n : Nat} → ⦃ _ : Num.MinusOK iNumNat n 1 ⦄ → Zero? (n - 1) → Zero? n

instance
  @0 zero? : {n : Nat} → Zero? n
  zero? {zero}  = ≡0
  zero? {suc n} = ≢0 (zero? {n})

fac : (n : Nat) → ⦃ @0 v : Zero? n ⦄ → Nat
fac 0          = 1
fac n ⦃ ≢0 v ⦄ = n * fac (n - 1) ⦃ v ⦄

{-# COMPILE AGDA2HS fac #-}

proof : fac 5 ≡ 120
proof = refl
```

Here, the only missing piece is that the `0` in the first clause of `fac` becomes `zero` in the Haskell code.

Making `agda2hs` emit `0` instead of `zero` would allow the above solution for covering basic "count down from n to 0" recursion.

No idea how useful this would be, though. :)

**Comment by jespercockx** [comment]
I still don't think this is the right thing to do, so I'm closing this.
