### ISSUE TITLE
Name conflict when translating sections

### ISSUE THREAD

**Issue by omelkonian** [agda/agda2hs#14]
When mixfix operators have unordered sections filled in, Agda generates a binding of a variable named `section`, which may clash with user-provided identifiers of the same name.

As an example:
```agda
inc : List Nat -> List Nat
inc = map (_+ 1)
{-# COMPILE AGDA2HS inc #-}
  -- ~> inc = map (\ section -> section + 1)

incBy : Nat -> List Nat -> List Nat
incBy section = map (_+ section)
{-# COMPILE AGDA2HS incBy #-}
  -- ~> incBy section = map (\ section -> section₁ + section)
```

**Comment by UlfNorell** [comment]
The problem is we're not picking the correct name for the binder. As you can see in the body we think the name of the binder is `section₁`, which is what you'd get in this example if printing the term from Agda. I believe this is broken for normal lambdas as well.

In this case we really should generate the section.
