### ISSUE TITLE
Don't overwrite import when using default type class instances from the `Prelude`

### ISSUE THREAD

**Issue by sarajuhosova** [agda/agda2hs#169]
Consider this code example where `Show₂` is used to define a `Show` instance for the `Identity` type:

```agda
open import Haskell.Prelude

record Identity (a : Set) : Set where
    field
        runIdentity : a
open Identity public

{-# COMPILE AGDA2HS Identity newtype #-}

showIdentity : ⦃ Show a ⦄ → Identity a → String
showIdentity record { runIdentity = id } = "Id < " ++ show id ++ " >"

{-# COMPILE AGDA2HS showIdentity #-}

instance
  iIdentityShow : ⦃ Show a ⦄ → Show (Identity a)
  iIdentityShow = record {Show₂ record {show = showIdentity}}

{-# COMPILE AGDA2HS iIdentityShow #-}
```

This compiles to the following Haskell code:

```hs
module DefaultShow where

import qualified Prelude as Show₂ (showList, showsPrec)

newtype Identity a = Identity{runIdentity :: a}

showIdentity :: Show a => Identity a -> String
showIdentity (Identity id) = "Id < " ++ show id ++ " >"

instance (Show a) => Show (Identity a) where
    showsPrec = Show₂.showsPrec
    showList = Show₂.showList
    show = showIdentity
```

However, if you try to compile this, you get a lot of "Not in scope" errors.
This is because the `import qualified Prelude as Show₂ (showList, showsPrec)` line in the generated Haskell code overwrites the implicit Prelude import and takes all the other constructs from the Prelude out of scope.

**Hacky fix:** There is a hacky fix for this, which is that the user has to add the following to their Agda code:
```hs
{-# FOREIGN AGDA2HS
import Prelude
#-}
```

<details>
<summary>Error Log</summary>

```
DefaultShow.hs:7:17: error:
    Not in scope: type constructor or class ‘Show’
  |
7 | showIdentity :: Show a => Identity a -> String
  |                 ^^^^

DefaultShow.hs:7:41: error:
    Not in scope: type constructor or class ‘String’
  |
7 | showIdentity :: Show a => Identity a -> String
  |                                         ^^^^^^

DefaultShow.hs:10:11: error:
    Not in scope: type constructor or class ‘Show’
   |
10 | instance (Show a) => Show (Identity a) where
   |           ^^^^

DefaultShow.hs:10:22: error:
    Not in scope: type constructor or class ‘Show’
   |
10 | instance (Show a) => Show (Identity a) where
   |                      ^^^^
```

</details>

**Comment by jespercockx** [comment]
There's three problems here:

1. `agda2hs` does not recognize that `Show₂` is supposed to be a minimal record, and thus generates definitions for `showsPrec` and `showList` that are bogus.
2. Due to buggy pretty-printing code in Agda, `agda2hs` thinks that the names `showsPrec` and `showList` are qualified
3. When generating the qualified import of `Prelude`, `agda2hs` forgets that there are other definitions from the Prelude that need to be imported.

I think I can fix 1 and 3 on the `agda2hs` side, but 2 is trickier since we rely on Agda's pretty-printer to detect when it is fine to print a name unqualified and if not, which qualifier was used in the Agda code.
