### ISSUE TITLE
variables in the prelude seem to pollute the name-space

### ISSUE THREAD

**Issue by patrikja** [agda/agda2hs#179]
https://github.com/agda/agda2hs/blob/87a23ebd6c617d6112a185f7709c32f126ecac5e/lib/Haskell/Prim.agda#LL28C3-L28C3

If a file importing the prelude tries to declare a short name like f or a it will clash with the variable declaration from Prim.
I currently work around it by hiding f from the prelude import, but I think Prim should perhaps use
private
  variable
     ...
or at least warn about these "stolen" top-level names.

Concrete examples:

```
open import Haskell.Prelude
f = \x -> x
```
or

```
open import Haskell.Prelude
variable 
  @0 a : Set
```
both complain about "Multiple definitions"

**Comment by jespercockx** [comment]
The reason for having these variables is because they are often used in Haskell type signatures, so you want to be able to write something like `foo : {{Functor f}} -> ...` in Agda as well. And I would argue that using a single letter for the name of a top-level function is not really good practice anyway..
