### ISSUE TITLE
Allow non-erased hidden arguments (but make them explicit)

### ISSUE THREAD

**Issue by flupe** [agda/agda2hs#217]
Currently, agda2hs doesn't allow functions to have _non-erased_ hidden arguments, unless they are `Set` or `Level`. I would like to propose we allow other kind of hidden arguments: we simply make them explicit on the Haskell side.

While this doesn't fit the philosophy of only making Haskell patterns available in Agda, I think there is a good motivation for it when doing intrinsic verification: [tactic arguments](https://agda.readthedocs.io/en/latest/language/implicit-arguments.html#tactic-arguments).

We can use such tactics on the Agda side to lighten the syntax, even though we care about the solutions on the Haskell side.

---

The example I have in mind is Jesper's [syntax for agda-core](https://github.com/jespercockx/agda-core/blob/main/Syntax.agda#L37):

```agda
data Term α where
  var    : (@0 x : Name) → {@(tactic auto) x∈α : x ∈ α} → Term α
```

Such a definition permits using names on the Agda side and letting Agda figure out indices in the global scope using a tactic. However, we want names to be erased and the index to be preserved.

**Comment by jespercockx** [comment]
This is a somewhat different way of using `agda2hs` than what we intended so far since there is no direct 1-to-1 correspondence between the concrete Agda syntax and Haskell syntax. However, I think it still makes sense because we are making use of the richer (erased) types on the Agda side to *derive* the actual Haskell program. So I think this is a sensible addition to make.
