### ISSUE TITLE
Dealing with partial functions

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda2hs#28]
Many commonly used Haskell functions are partial. Some examples from the Prelude: `head` and `tail`, `toEnum`, `take` and `drop`. There are two ways to deal with this that I can see:

1. Add an implicit proof argument that you are in the total fragment. For instance
   ```agda
   head : (xs : List a) → {NonEmpty xs} → a
   head [] {}
   head (x : _) = x
   ```
   The implicit argument will be erased when translating to Haskell.
2. Use an `error` postulate. To not compromise consistency, it would have to be restricted to inhabited types:
   ```agda
   postulate error : {inh : Inhabited a} → String → a

   head : {inh : Inhabited a} → List a → a
   head {inh = p} [] = error {inh = p} "Prelude.head: empty list"
   head (x : _) = x
   ```

I see some advantages with option 2:
- More faithful to the actual Haskell code.
- You don't have to prove that your program doesn't crash if you don't want to.
- There's a single type of proof objects (Inhabited) instead of different ones for each function, which means it could get some special treatment (for instance, allowing it to be solved with instance search, but not generating a constraint on the Haskell side).
- It lets you represent and reason about code that *can* actually crash.

There are some serious disadvantages though:
- If you actually want to prove crash-freeness it's a bit more awkward.
- Not proving crash-freeness means other properties you prove might not hold. For instance,
  ```agda
   f : Nat → Nat
   f zero    = 5
   f (suc n) = 5
 
   five : Nat
   five = f (head [])
 
   lem : ∀ n → f n ≡ 5
   lem zero    = refl
   lem (suc n) = refl
 
   prf : five ≡ 5
   prf = lem _
  ```

The last point suggests to me that we should spend the effort to ensure we only write total programs.

@omelkonian, @jmchapman Thoughts?

**Comment by jespercockx** [comment]
My suggestion would be to avoid partial functions as much as possible, since representing them faithfully on the Agda side is going to be awkward no matter what. There are several good alternative preludes such as [Relude](https://hackage.haskell.org/package/relude) that provide total versions of standard prelude function; you could consider targeting that instead of the standard prelude.

A third option if you really want to support partial functions, I think option 1 is the better alternative. Some counterarguments to your listed advantages of option 2:
- You can still define the function `error` to take a `@tactic` argument of the empty type, so on the surface level the code will look similar to option 2
- If you don't want to prove that your program is total, you can just have a blanket implicit argument of the empty type (or even a implicit module parameter)
- You can use `@tactic` arguments instead of instance search to resolve more complex cases. A tactic can even be made to detect empty types generically, something which is not possible with instance search.
- I'd argue that option 1 is actually better to reason about programs that crash, in particular because of the problem you mention below.

**Comment by jmchapman** [comment]
In general I agree that it's best to avoid partial functions. I think I prefer option 1 too. I am rather apprehensive about custom preludes for general reasons not specific to agda2hs.

Presumably if somebody wanted to use option 2 they would be free to do so?

**Comment by jmchapman** [comment]
I guess possible non-termination (or not obvious termination) could also be handled like 1 with an implicit arg (termination predicate or a wrapped nat, etc.).

**Comment by jmchapman** [comment]
Ulf's https://github.com/agda/agda2hs/pull/36:
```
error : {@(tactic absurd) i : ⊥} → String → a
error {i = ()} err

hd : (xs : List a) → ⦃ NonEmpty xs ⦄ → a
hd []      = error "hd: empty list"
hd (x ∷ _) = x
{-# COMPILE AGDA2HS hd #-}
```

This gives you the best of both options 1 and 2 I think. Can we close this?

**Comment by UlfNorell** [comment]
Yes.
