### ISSUE TITLE
how to use Show from Haskell.Prelude

### ISSUE THREAD

**Issue by jmchapman** [agda/agda2hs#50]
What is the intended way to derive a Show instance using `Haskell.Prelude`?

E.g.,
```
data Exp (a : Set) : Set where
  Var : a → Exp a
  Val : Nat → Exp a
  Add : Exp a → Exp a → Exp a

{-# COMPILE AGDA2HS Exp deriving Show #-}
```

I can postulate an instance

```
instance
  postulate
    expShow : ∀{a} → ⦃ Show a ⦄ → Show (Exp a)
```

Is this the intended approach or can I define my own instance? I see there is lots of useful machinery in `Haskell.Prim.Show` but `makeShow` is hidden for example.

Also, if I make use of the above:
```
postulate
  IO : Set → Set
  putStrLn : String → IO ⊤

main : IO ⊤
main = putStrLn $ show (Add (Val 2) (Val 2))
{-# COMPILE AGDA2HS main #-}
```
and then compile, then the following code is generated for the `main` function:
```
main :: IO ()
main = putStrLn $ showsPrec 0 (Add (Val 2) (Val 2)) ""
```
where I was hoping`show` would appear instead of `showsPrec`.

**Comment by UlfNorell** [comment]
Depending on whether you need it to evaluate at compile time you can postulate or define your own. Postulating is safer of course, since there's no danger of defining a show instance that doesn't match the derived instance, but on the other hand you want be able to prove any properties.

`makeShow` and `makeShowsPrec` could well be exported.

For the last problem, try adding a `--no-auto-inline` to `Haskell.Prim.Show`.

**Comment by jmchapman** [comment]
thanks for the help, I think I would go with postulating. I think it would nice to avoid inlining on the agda side as much as possible. @jespercockx tells me that auto-inlining will be disabled by default in the next release of agda (2.6.3).
