### ISSUE TITLE
Set up github actions to build and run tests

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda2hs#8]
or Travis I guess?

**Comment by UlfNorell** [comment]
It looks like Travis is rebuilding Agda (and other dependencies) for every build. Shouldn't these be cached?

**Comment by omelkonian** [comment]
> It looks like Travis is rebuilding Agda (and other dependencies) for every build. Shouldn't these be cached?

No, this shouldn't happen. I don't have access for some reason, but in my fork (using the same `.travis.yml`) everything is cached.
For instance, the latest build for PR #11 took only `1 min 50 sec`: https://travis-ci.com/github/omelkonian/agda2hs.

**Comment by UlfNorell** [comment]
The only thing I did after merging your PR was to go to Travis and flip the switch for this repo. Is there something else you need to do to enable caching?

**Comment by UlfNorell** [comment]
It worked for this one though: https://travis-ci.org/github/agda/agda2hs/builds/739992186
So maybe caches took a little while to get set up?? I guess we'll monitor and see if it stays working.

**Comment by UlfNorell** [comment]
Seems to not be working. @omelkonian did you have strong reasons to prefer Travis over github actions, otherwise I'm tempted to try to switch.

**Comment by omelkonian** [comment]
Indeed some builds do the whole installation again, but maybe it has to do with modifications to .cabal? For example, your new PR #17 run only for 4min, but my current PR #16 took 30min (maybe because I added `syb` to the package list?).

No strong reasons for picking Travis, it was just straightforward to add.
In any case, if you think caching can be effortlessly handled using GH-actions, please go ahead and switch.

**Comment by UlfNorell** [comment]
I'll do some experiments.

**Comment by UlfNorell** [comment]
Fixed by #19
