### ISSUE TITLE
Support for copatterns

### ISSUE THREAD

**Issue by flupe** [agda/agda2hs#98]
It looks like copatterns are not currently supported. This is a problem for coinductive records since this looks like the only way to do proper coinduction (without sized types).

```agda
{-# OPTIONS --guardedness #-}
module Copatterns where

open import Haskell.Prelude

record Colist (a : Set) : Set where
  coinductive
  field
    hd : a
    tl : Colist a
open Colist public

{-# COMPILE AGDA2HS Colist #-}

repeat : a → Colist a
repeat x .hd = x
repeat x .tl = repeat x

{-# COMPILE AGDA2HS repeat #-}
```

compiles to:

```haskell
module Copatterns where

data Colist a = Colist{hd :: a, tl :: Colist a}

repeat :: a -> Colist a
repeat x Copatterns.Colist.hd = x
repeat x Copatterns.Colist.tl = repeat x
```

(which is, of course, invalid Haskell)

**Comment by jespercockx** [comment]
I'm looking into implementing this, but it seems to be rather tricky to support the general case. In particular, we would have to do the following:
- Gather all clauses that have equivalent patterns (ignoring copatterns).
- "Align" the patterns of these clauses so they use the same telescope.
- Translate the copatterns of these clauses in a kind of case tree.
- Use this case tree to construct a nested record expression from the right-hand sides of the clauses.

This actually seems like it goes against the philosophy of Agda2Hs to provide a "straightforward" mapping from Agda to Haskell. Instead, we should think about what *Haskell* features we want to support by using copatterns in Agda. Here's what I can think of:

- Coinductive datatypes: for this we have #99 
- Instances of type classes: for this we actually already support copatterns

Note that I am *not* listing Haskell `record` expressions, since we already have a more direct way to represent them in Agda. Hence my proposal would be to simply *forbid* general copatterns in regular function definitions, and instead only support coinduction through the dedicated `Thunk` type.
